blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/AndrewWalsh/openapi-spec-generator/discussions
    about: Please discuss non bug-related topics there
